#!/bin/bash
# Deploys app3 from version control, runs tests and if tests pass, runs new version of the app. If tests fail or any other error, sends email.
 
# Write some HTTP headers to make Nginx happy
echo -e "Content-type: text/html\n"
 
# Variables
DIRECTORY="$PWD/public"
VCS_URL=git@github.com:henno/foo.git
OUTPUT=''
 
log() {
    # Output immediately (for terminal and web)
    echo -e $1
 
    # Collect OUTPUT (for sending email later)
    OUTPUT+="$1"$'\n'
}
 
cmd() {
    log "Doing '$@'"
 
    # Run the command and capture its output and exit code
    COMMAND_OUTPUT=`$@ 2>&1`
    COMMAND_EXIT_CODE=$?
 
    # Add command output to OUTPUT
    OUTPUT+=$COMMAND_OUTPUT$'\n'
 
    # Send the command output to stdout, too
    echo -e $COMMAND_OUTPUT$'\n'
 
    if [[ $COMMAND_EXIT_CODE -ne 0 ]]; then
 
        log "The previous command returned non-zero exit code. Aborting."
 
        # Send email to me
        mail -s 'message subject' -aFrom:app3@fadsghafdhdfhjnbb.club  henno.taht@gmail.com <<< $OUTPUT
 
        # Stop the script
        exit $?
    fi
}
 
        log "Updating the project"
 
        # Change potentially changed files (only tracked ones) back to the state they were originally in Github
        cmd "git reset --hard"
 
        # Pull the new commits from Github
        cmd 'git pull'
 

# Run tests
cmd 'npm run test'